// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    FrameworkLink: typeof import('./src/components/FrameworkLink.vue')['default']
    FreshFishProducts: typeof import('./src/components/FreshFishProducts.vue')['default']
    HfdFeatureSection: typeof import('./src/components/HfdFeatureSection.vue')['default']
    HfdFishCategories: typeof import('./src/components/HfdFishCategories.vue')['default']
    HfdFooter: typeof import('./src/components/HfdFooter.vue')['default']
    HfdHeaderImage: typeof import('./src/components/HfdHeaderImage.vue')['default']
    LobsterPriceBanner: typeof import('./src/components/LobsterPriceBanner.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellFishProducts: typeof import('./src/components/ShellFishProducts.vue')['default']
    SmokedFishProducts: typeof import('./src/components/SmokedFishProducts.vue')['default']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
  }
}
